#include <iostream>
#include "tjsTypes.h"
#include "tvpgl.h"
int main() {
  TVPInitTVPGL();
  int missing = 0;
  if (!TVPAlphaBlend) { std::cerr << "null: TVPAlphaBlend\n"; ++missing; }
  if (!TVPAlphaBlend_HDA) { std::cerr << "null: TVPAlphaBlend_HDA\n"; ++missing; }
  if (!TVPAlphaBlend_o) { std::cerr << "null: TVPAlphaBlend_o\n"; ++missing; }
  if (!TVPAlphaBlend_HDA_o) { std::cerr << "null: TVPAlphaBlend_HDA_o\n"; ++missing; }
  if (!TVPAlphaBlend_d) { std::cerr << "null: TVPAlphaBlend_d\n"; ++missing; }
  if (!TVPAlphaBlend_a) { std::cerr << "null: TVPAlphaBlend_a\n"; ++missing; }
  if (!TVPAlphaBlend_do) { std::cerr << "null: TVPAlphaBlend_do\n"; ++missing; }
  if (!TVPAlphaBlend_ao) { std::cerr << "null: TVPAlphaBlend_ao\n"; ++missing; }
  if (!TVPAlphaColorMat) { std::cerr << "null: TVPAlphaColorMat\n"; ++missing; }
  if (!TVPAdditiveAlphaBlend) { std::cerr << "null: TVPAdditiveAlphaBlend\n"; ++missing; }
  if (!TVPAdditiveAlphaBlend_HDA) { std::cerr << "null: TVPAdditiveAlphaBlend_HDA\n"; ++missing; }
  if (!TVPAdditiveAlphaBlend_o) { std::cerr << "null: TVPAdditiveAlphaBlend_o\n"; ++missing; }
  if (!TVPAdditiveAlphaBlend_HDA_o) { std::cerr << "null: TVPAdditiveAlphaBlend_HDA_o\n"; ++missing; }
  if (!TVPAdditiveAlphaBlend_a) { std::cerr << "null: TVPAdditiveAlphaBlend_a\n"; ++missing; }
  if (!TVPAdditiveAlphaBlend_ao) { std::cerr << "null: TVPAdditiveAlphaBlend_ao\n"; ++missing; }
  if (!TVPConvertAdditiveAlphaToAlpha) { std::cerr << "null: TVPConvertAdditiveAlphaToAlpha\n"; ++missing; }
  if (!TVPConvertAlphaToAdditiveAlpha) { std::cerr << "null: TVPConvertAlphaToAdditiveAlpha\n"; ++missing; }
  if (!TVPStretchAlphaBlend) { std::cerr << "null: TVPStretchAlphaBlend\n"; ++missing; }
  if (!TVPStretchAlphaBlend_HDA) { std::cerr << "null: TVPStretchAlphaBlend_HDA\n"; ++missing; }
  if (!TVPStretchAlphaBlend_o) { std::cerr << "null: TVPStretchAlphaBlend_o\n"; ++missing; }
  if (!TVPStretchAlphaBlend_HDA_o) { std::cerr << "null: TVPStretchAlphaBlend_HDA_o\n"; ++missing; }
  if (!TVPStretchAlphaBlend_d) { std::cerr << "null: TVPStretchAlphaBlend_d\n"; ++missing; }
  if (!TVPStretchAlphaBlend_a) { std::cerr << "null: TVPStretchAlphaBlend_a\n"; ++missing; }
  if (!TVPStretchAlphaBlend_do) { std::cerr << "null: TVPStretchAlphaBlend_do\n"; ++missing; }
  if (!TVPStretchAlphaBlend_ao) { std::cerr << "null: TVPStretchAlphaBlend_ao\n"; ++missing; }
  if (!TVPStretchAdditiveAlphaBlend) { std::cerr << "null: TVPStretchAdditiveAlphaBlend\n"; ++missing; }
  if (!TVPInterpStretchAdditiveAlphaBlend) { std::cerr << "null: TVPInterpStretchAdditiveAlphaBlend\n"; ++missing; }
  if (!TVPStretchAdditiveAlphaBlend_HDA) { std::cerr << "null: TVPStretchAdditiveAlphaBlend_HDA\n"; ++missing; }
  if (!TVPStretchAdditiveAlphaBlend_o) { std::cerr << "null: TVPStretchAdditiveAlphaBlend_o\n"; ++missing; }
  if (!TVPInterpStretchAdditiveAlphaBlend_o) { std::cerr << "null: TVPInterpStretchAdditiveAlphaBlend_o\n"; ++missing; }
  if (!TVPStretchAdditiveAlphaBlend_HDA_o) { std::cerr << "null: TVPStretchAdditiveAlphaBlend_HDA_o\n"; ++missing; }
  if (!TVPStretchAdditiveAlphaBlend_a) { std::cerr << "null: TVPStretchAdditiveAlphaBlend_a\n"; ++missing; }
  if (!TVPStretchAdditiveAlphaBlend_ao) { std::cerr << "null: TVPStretchAdditiveAlphaBlend_ao\n"; ++missing; }
  if (!TVPLinTransAlphaBlend) { std::cerr << "null: TVPLinTransAlphaBlend\n"; ++missing; }
  if (!TVPLinTransAlphaBlend_HDA) { std::cerr << "null: TVPLinTransAlphaBlend_HDA\n"; ++missing; }
  if (!TVPLinTransAlphaBlend_o) { std::cerr << "null: TVPLinTransAlphaBlend_o\n"; ++missing; }
  if (!TVPLinTransAlphaBlend_HDA_o) { std::cerr << "null: TVPLinTransAlphaBlend_HDA_o\n"; ++missing; }
  if (!TVPLinTransAlphaBlend_d) { std::cerr << "null: TVPLinTransAlphaBlend_d\n"; ++missing; }
  if (!TVPLinTransAlphaBlend_a) { std::cerr << "null: TVPLinTransAlphaBlend_a\n"; ++missing; }
  if (!TVPLinTransAlphaBlend_do) { std::cerr << "null: TVPLinTransAlphaBlend_do\n"; ++missing; }
  if (!TVPLinTransAlphaBlend_ao) { std::cerr << "null: TVPLinTransAlphaBlend_ao\n"; ++missing; }
  if (!TVPLinTransAdditiveAlphaBlend) { std::cerr << "null: TVPLinTransAdditiveAlphaBlend\n"; ++missing; }
  if (!TVPInterpLinTransAdditiveAlphaBlend) { std::cerr << "null: TVPInterpLinTransAdditiveAlphaBlend\n"; ++missing; }
  if (!TVPLinTransAdditiveAlphaBlend_HDA) { std::cerr << "null: TVPLinTransAdditiveAlphaBlend_HDA\n"; ++missing; }
  if (!TVPLinTransAdditiveAlphaBlend_o) { std::cerr << "null: TVPLinTransAdditiveAlphaBlend_o\n"; ++missing; }
  if (!TVPInterpLinTransAdditiveAlphaBlend_o) { std::cerr << "null: TVPInterpLinTransAdditiveAlphaBlend_o\n"; ++missing; }
  if (!TVPLinTransAdditiveAlphaBlend_HDA_o) { std::cerr << "null: TVPLinTransAdditiveAlphaBlend_HDA_o\n"; ++missing; }
  if (!TVPLinTransAdditiveAlphaBlend_a) { std::cerr << "null: TVPLinTransAdditiveAlphaBlend_a\n"; ++missing; }
  if (!TVPLinTransAdditiveAlphaBlend_ao) { std::cerr << "null: TVPLinTransAdditiveAlphaBlend_ao\n"; ++missing; }
  if (!TVPCopyOpaqueImage) { std::cerr << "null: TVPCopyOpaqueImage\n"; ++missing; }
  if (!TVPConstAlphaBlend) { std::cerr << "null: TVPConstAlphaBlend\n"; ++missing; }
  if (!TVPConstAlphaBlend_HDA) { std::cerr << "null: TVPConstAlphaBlend_HDA\n"; ++missing; }
  if (!TVPConstAlphaBlend_d) { std::cerr << "null: TVPConstAlphaBlend_d\n"; ++missing; }
  if (!TVPConstAlphaBlend_a) { std::cerr << "null: TVPConstAlphaBlend_a\n"; ++missing; }
  if (!TVPStretchCopyOpaqueImage) { std::cerr << "null: TVPStretchCopyOpaqueImage\n"; ++missing; }
  if (!TVPStretchConstAlphaBlend) { std::cerr << "null: TVPStretchConstAlphaBlend\n"; ++missing; }
  if (!TVPInterpStretchConstAlphaBlend) { std::cerr << "null: TVPInterpStretchConstAlphaBlend\n"; ++missing; }
  if (!TVPStretchConstAlphaBlend_HDA) { std::cerr << "null: TVPStretchConstAlphaBlend_HDA\n"; ++missing; }
  if (!TVPStretchConstAlphaBlend_d) { std::cerr << "null: TVPStretchConstAlphaBlend_d\n"; ++missing; }
  if (!TVPStretchConstAlphaBlend_a) { std::cerr << "null: TVPStretchConstAlphaBlend_a\n"; ++missing; }
  if (!TVPLinTransCopyOpaqueImage) { std::cerr << "null: TVPLinTransCopyOpaqueImage\n"; ++missing; }
  if (!TVPLinTransConstAlphaBlend) { std::cerr << "null: TVPLinTransConstAlphaBlend\n"; ++missing; }
  if (!TVPInterpLinTransConstAlphaBlend) { std::cerr << "null: TVPInterpLinTransConstAlphaBlend\n"; ++missing; }
  if (!TVPLinTransConstAlphaBlend_HDA) { std::cerr << "null: TVPLinTransConstAlphaBlend_HDA\n"; ++missing; }
  if (!TVPLinTransConstAlphaBlend_d) { std::cerr << "null: TVPLinTransConstAlphaBlend_d\n"; ++missing; }
  if (!TVPLinTransConstAlphaBlend_a) { std::cerr << "null: TVPLinTransConstAlphaBlend_a\n"; ++missing; }
  if (!TVPConstAlphaBlend_SD) { std::cerr << "null: TVPConstAlphaBlend_SD\n"; ++missing; }
  if (!TVPConstAlphaBlend_SD_a) { std::cerr << "null: TVPConstAlphaBlend_SD_a\n"; ++missing; }
  if (!TVPConstAlphaBlend_SD_d) { std::cerr << "null: TVPConstAlphaBlend_SD_d\n"; ++missing; }
  if (!TVPInitUnivTransBlendTable) { std::cerr << "null: TVPInitUnivTransBlendTable\n"; ++missing; }
  if (!TVPInitUnivTransBlendTable_d) { std::cerr << "null: TVPInitUnivTransBlendTable_d\n"; ++missing; }
  if (!TVPInitUnivTransBlendTable_a) { std::cerr << "null: TVPInitUnivTransBlendTable_a\n"; ++missing; }
  if (!TVPUnivTransBlend) { std::cerr << "null: TVPUnivTransBlend\n"; ++missing; }
  if (!TVPUnivTransBlend_switch) { std::cerr << "null: TVPUnivTransBlend_switch\n"; ++missing; }
  if (!TVPUnivTransBlend_d) { std::cerr << "null: TVPUnivTransBlend_d\n"; ++missing; }
  if (!TVPUnivTransBlend_switch_d) { std::cerr << "null: TVPUnivTransBlend_switch_d\n"; ++missing; }
  if (!TVPUnivTransBlend_a) { std::cerr << "null: TVPUnivTransBlend_a\n"; ++missing; }
  if (!TVPUnivTransBlend_switch_a) { std::cerr << "null: TVPUnivTransBlend_switch_a\n"; ++missing; }
  if (!TVPApplyColorMap) { std::cerr << "null: TVPApplyColorMap\n"; ++missing; }
  if (!TVPApplyColorMap_o) { std::cerr << "null: TVPApplyColorMap_o\n"; ++missing; }
  if (!TVPApplyColorMap65) { std::cerr << "null: TVPApplyColorMap65\n"; ++missing; }
  if (!TVPApplyColorMap65_o) { std::cerr << "null: TVPApplyColorMap65_o\n"; ++missing; }
  if (!TVPApplyColorMap_HDA) { std::cerr << "null: TVPApplyColorMap_HDA\n"; ++missing; }
  if (!TVPApplyColorMap_HDA_o) { std::cerr << "null: TVPApplyColorMap_HDA_o\n"; ++missing; }
  if (!TVPApplyColorMap65_HDA) { std::cerr << "null: TVPApplyColorMap65_HDA\n"; ++missing; }
  if (!TVPApplyColorMap65_HDA_o) { std::cerr << "null: TVPApplyColorMap65_HDA_o\n"; ++missing; }
  if (!TVPApplyColorMap_d) { std::cerr << "null: TVPApplyColorMap_d\n"; ++missing; }
  if (!TVPApplyColorMap65_d) { std::cerr << "null: TVPApplyColorMap65_d\n"; ++missing; }
  if (!TVPApplyColorMap_a) { std::cerr << "null: TVPApplyColorMap_a\n"; ++missing; }
  if (!TVPApplyColorMap65_a) { std::cerr << "null: TVPApplyColorMap65_a\n"; ++missing; }
  if (!TVPApplyColorMap_do) { std::cerr << "null: TVPApplyColorMap_do\n"; ++missing; }
  if (!TVPApplyColorMap65_do) { std::cerr << "null: TVPApplyColorMap65_do\n"; ++missing; }
  if (!TVPApplyColorMap_ao) { std::cerr << "null: TVPApplyColorMap_ao\n"; ++missing; }
  if (!TVPApplyColorMap65_ao) { std::cerr << "null: TVPApplyColorMap65_ao\n"; ++missing; }
  if (!TVPConstColorAlphaBlend) { std::cerr << "null: TVPConstColorAlphaBlend\n"; ++missing; }
  if (!TVPConstColorAlphaBlend_d) { std::cerr << "null: TVPConstColorAlphaBlend_d\n"; ++missing; }
  if (!TVPConstColorAlphaBlend_a) { std::cerr << "null: TVPConstColorAlphaBlend_a\n"; ++missing; }
  if (!TVPRemoveConstOpacity) { std::cerr << "null: TVPRemoveConstOpacity\n"; ++missing; }
  if (!TVPRemoveOpacity) { std::cerr << "null: TVPRemoveOpacity\n"; ++missing; }
  if (!TVPRemoveOpacity_o) { std::cerr << "null: TVPRemoveOpacity_o\n"; ++missing; }
  if (!TVPRemoveOpacity65) { std::cerr << "null: TVPRemoveOpacity65\n"; ++missing; }
  if (!TVPRemoveOpacity65_o) { std::cerr << "null: TVPRemoveOpacity65_o\n"; ++missing; }
  if (!TVPAddBlend) { std::cerr << "null: TVPAddBlend\n"; ++missing; }
  if (!TVPAddBlend_HDA) { std::cerr << "null: TVPAddBlend_HDA\n"; ++missing; }
  if (!TVPAddBlend_o) { std::cerr << "null: TVPAddBlend_o\n"; ++missing; }
  if (!TVPAddBlend_HDA_o) { std::cerr << "null: TVPAddBlend_HDA_o\n"; ++missing; }
  if (!TVPSubBlend) { std::cerr << "null: TVPSubBlend\n"; ++missing; }
  if (!TVPSubBlend_HDA) { std::cerr << "null: TVPSubBlend_HDA\n"; ++missing; }
  if (!TVPSubBlend_o) { std::cerr << "null: TVPSubBlend_o\n"; ++missing; }
  if (!TVPSubBlend_HDA_o) { std::cerr << "null: TVPSubBlend_HDA_o\n"; ++missing; }
  if (!TVPMulBlend) { std::cerr << "null: TVPMulBlend\n"; ++missing; }
  if (!TVPMulBlend_HDA) { std::cerr << "null: TVPMulBlend_HDA\n"; ++missing; }
  if (!TVPMulBlend_o) { std::cerr << "null: TVPMulBlend_o\n"; ++missing; }
  if (!TVPMulBlend_HDA_o) { std::cerr << "null: TVPMulBlend_HDA_o\n"; ++missing; }
  if (!TVPColorDodgeBlend) { std::cerr << "null: TVPColorDodgeBlend\n"; ++missing; }
  if (!TVPColorDodgeBlend_HDA) { std::cerr << "null: TVPColorDodgeBlend_HDA\n"; ++missing; }
  if (!TVPColorDodgeBlend_o) { std::cerr << "null: TVPColorDodgeBlend_o\n"; ++missing; }
  if (!TVPColorDodgeBlend_HDA_o) { std::cerr << "null: TVPColorDodgeBlend_HDA_o\n"; ++missing; }
  if (!TVPDarkenBlend) { std::cerr << "null: TVPDarkenBlend\n"; ++missing; }
  if (!TVPDarkenBlend_HDA) { std::cerr << "null: TVPDarkenBlend_HDA\n"; ++missing; }
  if (!TVPDarkenBlend_o) { std::cerr << "null: TVPDarkenBlend_o\n"; ++missing; }
  if (!TVPDarkenBlend_HDA_o) { std::cerr << "null: TVPDarkenBlend_HDA_o\n"; ++missing; }
  if (!TVPLightenBlend) { std::cerr << "null: TVPLightenBlend\n"; ++missing; }
  if (!TVPLightenBlend_HDA) { std::cerr << "null: TVPLightenBlend_HDA\n"; ++missing; }
  if (!TVPLightenBlend_o) { std::cerr << "null: TVPLightenBlend_o\n"; ++missing; }
  if (!TVPLightenBlend_HDA_o) { std::cerr << "null: TVPLightenBlend_HDA_o\n"; ++missing; }
  if (!TVPScreenBlend) { std::cerr << "null: TVPScreenBlend\n"; ++missing; }
  if (!TVPScreenBlend_HDA) { std::cerr << "null: TVPScreenBlend_HDA\n"; ++missing; }
  if (!TVPScreenBlend_o) { std::cerr << "null: TVPScreenBlend_o\n"; ++missing; }
  if (!TVPScreenBlend_HDA_o) { std::cerr << "null: TVPScreenBlend_HDA_o\n"; ++missing; }
  if (!TVPStretchCopy) { std::cerr << "null: TVPStretchCopy\n"; ++missing; }
  if (!TVPInterpStretchCopy) { std::cerr << "null: TVPInterpStretchCopy\n"; ++missing; }
  if (!TVPFastLinearInterpH2F) { std::cerr << "null: TVPFastLinearInterpH2F\n"; ++missing; }
  if (!TVPFastLinearInterpH2B) { std::cerr << "null: TVPFastLinearInterpH2B\n"; ++missing; }
  if (!TVPFastLinearInterpV2) { std::cerr << "null: TVPFastLinearInterpV2\n"; ++missing; }
  if (!TVPStretchColorCopy) { std::cerr << "null: TVPStretchColorCopy\n"; ++missing; }
  if (!TVPLinTransCopy) { std::cerr << "null: TVPLinTransCopy\n"; ++missing; }
  if (!TVPInterpLinTransCopy) { std::cerr << "null: TVPInterpLinTransCopy\n"; ++missing; }
  if (!TVPLinTransColorCopy) { std::cerr << "null: TVPLinTransColorCopy\n"; ++missing; }
  if (!TVPMakeAlphaFromKey) { std::cerr << "null: TVPMakeAlphaFromKey\n"; ++missing; }
  if (!TVPCopyMask) { std::cerr << "null: TVPCopyMask\n"; ++missing; }
  if (!TVPCopyColor) { std::cerr << "null: TVPCopyColor\n"; ++missing; }
  if (!TVPBindMaskToMain) { std::cerr << "null: TVPBindMaskToMain\n"; ++missing; }
  if (!TVPFillARGB) { std::cerr << "null: TVPFillARGB\n"; ++missing; }
  if (!TVPFillARGB_NC) { std::cerr << "null: TVPFillARGB_NC\n"; ++missing; }
  if (!TVPFillColor) { std::cerr << "null: TVPFillColor\n"; ++missing; }
  if (!TVPFillMask) { std::cerr << "null: TVPFillMask\n"; ++missing; }
  if (!TVPAddSubVertSum16) { std::cerr << "null: TVPAddSubVertSum16\n"; ++missing; }
  if (!TVPAddSubVertSum16_d) { std::cerr << "null: TVPAddSubVertSum16_d\n"; ++missing; }
  if (!TVPAddSubVertSum32) { std::cerr << "null: TVPAddSubVertSum32\n"; ++missing; }
  if (!TVPAddSubVertSum32_d) { std::cerr << "null: TVPAddSubVertSum32_d\n"; ++missing; }
  if (!TVPDoBoxBlurAvg16) { std::cerr << "null: TVPDoBoxBlurAvg16\n"; ++missing; }
  if (!TVPDoBoxBlurAvg16_d) { std::cerr << "null: TVPDoBoxBlurAvg16_d\n"; ++missing; }
  if (!TVPDoBoxBlurAvg32) { std::cerr << "null: TVPDoBoxBlurAvg32\n"; ++missing; }
  if (!TVPDoBoxBlurAvg32_d) { std::cerr << "null: TVPDoBoxBlurAvg32_d\n"; ++missing; }
  if (!TVPSwapLine8) { std::cerr << "null: TVPSwapLine8\n"; ++missing; }
  if (!TVPSwapLine32) { std::cerr << "null: TVPSwapLine32\n"; ++missing; }
  if (!TVPReverse8) { std::cerr << "null: TVPReverse8\n"; ++missing; }
  if (!TVPReverse32) { std::cerr << "null: TVPReverse32\n"; ++missing; }
  if (!TVPDoGrayScale) { std::cerr << "null: TVPDoGrayScale\n"; ++missing; }
  if (!TVPInitGammaAdjustTempData) { std::cerr << "null: TVPInitGammaAdjustTempData\n"; ++missing; }
  if (!TVPUninitGammaAdjustTempData) { std::cerr << "null: TVPUninitGammaAdjustTempData\n"; ++missing; }
  if (!TVPAdjustGamma) { std::cerr << "null: TVPAdjustGamma\n"; ++missing; }
  if (!TVPAdjustGamma_a) { std::cerr << "null: TVPAdjustGamma_a\n"; ++missing; }
  if (!TVPChBlurMulCopy65) { std::cerr << "null: TVPChBlurMulCopy65\n"; ++missing; }
  if (!TVPChBlurAddMulCopy65) { std::cerr << "null: TVPChBlurAddMulCopy65\n"; ++missing; }
  if (!TVPChBlurCopy65) { std::cerr << "null: TVPChBlurCopy65\n"; ++missing; }
  if (!TVPChBlurMulCopy) { std::cerr << "null: TVPChBlurMulCopy\n"; ++missing; }
  if (!TVPChBlurAddMulCopy) { std::cerr << "null: TVPChBlurAddMulCopy\n"; ++missing; }
  if (!TVPChBlurCopy) { std::cerr << "null: TVPChBlurCopy\n"; ++missing; }
  if (!TVPBLExpand1BitTo8BitPal) { std::cerr << "null: TVPBLExpand1BitTo8BitPal\n"; ++missing; }
  if (!TVPBLExpand1BitTo8Bit) { std::cerr << "null: TVPBLExpand1BitTo8Bit\n"; ++missing; }
  if (!TVPBLExpand1BitTo32BitPal) { std::cerr << "null: TVPBLExpand1BitTo32BitPal\n"; ++missing; }
  if (!TVPBLExpand4BitTo8BitPal) { std::cerr << "null: TVPBLExpand4BitTo8BitPal\n"; ++missing; }
  if (!TVPBLExpand4BitTo8Bit) { std::cerr << "null: TVPBLExpand4BitTo8Bit\n"; ++missing; }
  if (!TVPBLExpand4BitTo32BitPal) { std::cerr << "null: TVPBLExpand4BitTo32BitPal\n"; ++missing; }
  if (!TVPBLExpand8BitTo8BitPal) { std::cerr << "null: TVPBLExpand8BitTo8BitPal\n"; ++missing; }
  if (!TVPBLExpand8BitTo32BitPal) { std::cerr << "null: TVPBLExpand8BitTo32BitPal\n"; ++missing; }
  if (!TVPExpand8BitTo32BitGray) { std::cerr << "null: TVPExpand8BitTo32BitGray\n"; ++missing; }
  if (!TVPBLConvert15BitTo8Bit) { std::cerr << "null: TVPBLConvert15BitTo8Bit\n"; ++missing; }
  if (!TVPBLConvert15BitTo32Bit) { std::cerr << "null: TVPBLConvert15BitTo32Bit\n"; ++missing; }
  if (!TVPBLConvert24BitTo8Bit) { std::cerr << "null: TVPBLConvert24BitTo8Bit\n"; ++missing; }
  if (!TVPBLConvert24BitTo32Bit) { std::cerr << "null: TVPBLConvert24BitTo32Bit\n"; ++missing; }
  if (!TVPConvert24BitTo32Bit) { std::cerr << "null: TVPConvert24BitTo32Bit\n"; ++missing; }
  if (!TVPBLConvert32BitTo8Bit) { std::cerr << "null: TVPBLConvert32BitTo8Bit\n"; ++missing; }
  if (!TVPBLConvert32BitTo32Bit_NoneAlpha) { std::cerr << "null: TVPBLConvert32BitTo32Bit_NoneAlpha\n"; ++missing; }
  if (!TVPBLConvert32BitTo32Bit_MulAddAlpha) { std::cerr << "null: TVPBLConvert32BitTo32Bit_MulAddAlpha\n"; ++missing; }
  if (!TVPBLConvert32BitTo32Bit_AddAlpha) { std::cerr << "null: TVPBLConvert32BitTo32Bit_AddAlpha\n"; ++missing; }
  if (!TVPDither32BitTo16Bit565) { std::cerr << "null: TVPDither32BitTo16Bit565\n"; ++missing; }
  if (!TVPDither32BitTo16Bit555) { std::cerr << "null: TVPDither32BitTo16Bit555\n"; ++missing; }
  if (!TVPDither32BitTo8Bit) { std::cerr << "null: TVPDither32BitTo8Bit\n"; ++missing; }
  if (!TVPTLG5ComposeColors3To4) { std::cerr << "null: TVPTLG5ComposeColors3To4\n"; ++missing; }
  if (!TVPTLG5ComposeColors4To4) { std::cerr << "null: TVPTLG5ComposeColors4To4\n"; ++missing; }
  if (!TVPTLG5DecompressSlide) { std::cerr << "null: TVPTLG5DecompressSlide\n"; ++missing; }
  if (!TVPTLG6DecodeGolombValuesForFirst) { std::cerr << "null: TVPTLG6DecodeGolombValuesForFirst\n"; ++missing; }
  if (!TVPTLG6DecodeGolombValues) { std::cerr << "null: TVPTLG6DecodeGolombValues\n"; ++missing; }
  if (!TVPTLG6DecodeLineGeneric) { std::cerr << "null: TVPTLG6DecodeLineGeneric\n"; ++missing; }
  if (!TVPTLG6DecodeLine) { std::cerr << "null: TVPTLG6DecodeLine\n"; ++missing; }
  if (!TVPPsAlphaBlend) { std::cerr << "null: TVPPsAlphaBlend\n"; ++missing; }
  if (!TVPPsAlphaBlend_o) { std::cerr << "null: TVPPsAlphaBlend_o\n"; ++missing; }
  if (!TVPPsAlphaBlend_HDA) { std::cerr << "null: TVPPsAlphaBlend_HDA\n"; ++missing; }
  if (!TVPPsAlphaBlend_HDA_o) { std::cerr << "null: TVPPsAlphaBlend_HDA_o\n"; ++missing; }
  if (!TVPPsAddBlend) { std::cerr << "null: TVPPsAddBlend\n"; ++missing; }
  if (!TVPPsAddBlend_o) { std::cerr << "null: TVPPsAddBlend_o\n"; ++missing; }
  if (!TVPPsAddBlend_HDA) { std::cerr << "null: TVPPsAddBlend_HDA\n"; ++missing; }
  if (!TVPPsAddBlend_HDA_o) { std::cerr << "null: TVPPsAddBlend_HDA_o\n"; ++missing; }
  if (!TVPPsSubBlend) { std::cerr << "null: TVPPsSubBlend\n"; ++missing; }
  if (!TVPPsSubBlend_o) { std::cerr << "null: TVPPsSubBlend_o\n"; ++missing; }
  if (!TVPPsSubBlend_HDA) { std::cerr << "null: TVPPsSubBlend_HDA\n"; ++missing; }
  if (!TVPPsSubBlend_HDA_o) { std::cerr << "null: TVPPsSubBlend_HDA_o\n"; ++missing; }
  if (!TVPPsMulBlend) { std::cerr << "null: TVPPsMulBlend\n"; ++missing; }
  if (!TVPPsMulBlend_o) { std::cerr << "null: TVPPsMulBlend_o\n"; ++missing; }
  if (!TVPPsMulBlend_HDA) { std::cerr << "null: TVPPsMulBlend_HDA\n"; ++missing; }
  if (!TVPPsMulBlend_HDA_o) { std::cerr << "null: TVPPsMulBlend_HDA_o\n"; ++missing; }
  if (!TVPPsScreenBlend) { std::cerr << "null: TVPPsScreenBlend\n"; ++missing; }
  if (!TVPPsScreenBlend_o) { std::cerr << "null: TVPPsScreenBlend_o\n"; ++missing; }
  if (!TVPPsScreenBlend_HDA) { std::cerr << "null: TVPPsScreenBlend_HDA\n"; ++missing; }
  if (!TVPPsScreenBlend_HDA_o) { std::cerr << "null: TVPPsScreenBlend_HDA_o\n"; ++missing; }
  if (!TVPPsOverlayBlend) { std::cerr << "null: TVPPsOverlayBlend\n"; ++missing; }
  if (!TVPPsOverlayBlend_o) { std::cerr << "null: TVPPsOverlayBlend_o\n"; ++missing; }
  if (!TVPPsOverlayBlend_HDA) { std::cerr << "null: TVPPsOverlayBlend_HDA\n"; ++missing; }
  if (!TVPPsOverlayBlend_HDA_o) { std::cerr << "null: TVPPsOverlayBlend_HDA_o\n"; ++missing; }
  if (!TVPPsHardLightBlend) { std::cerr << "null: TVPPsHardLightBlend\n"; ++missing; }
  if (!TVPPsHardLightBlend_o) { std::cerr << "null: TVPPsHardLightBlend_o\n"; ++missing; }
  if (!TVPPsHardLightBlend_HDA) { std::cerr << "null: TVPPsHardLightBlend_HDA\n"; ++missing; }
  if (!TVPPsHardLightBlend_HDA_o) { std::cerr << "null: TVPPsHardLightBlend_HDA_o\n"; ++missing; }
  if (!TVPPsSoftLightBlend) { std::cerr << "null: TVPPsSoftLightBlend\n"; ++missing; }
  if (!TVPPsSoftLightBlend_o) { std::cerr << "null: TVPPsSoftLightBlend_o\n"; ++missing; }
  if (!TVPPsSoftLightBlend_HDA) { std::cerr << "null: TVPPsSoftLightBlend_HDA\n"; ++missing; }
  if (!TVPPsSoftLightBlend_HDA_o) { std::cerr << "null: TVPPsSoftLightBlend_HDA_o\n"; ++missing; }
  if (!TVPPsColorDodgeBlend) { std::cerr << "null: TVPPsColorDodgeBlend\n"; ++missing; }
  if (!TVPPsColorDodgeBlend_o) { std::cerr << "null: TVPPsColorDodgeBlend_o\n"; ++missing; }
  if (!TVPPsColorDodgeBlend_HDA) { std::cerr << "null: TVPPsColorDodgeBlend_HDA\n"; ++missing; }
  if (!TVPPsColorDodgeBlend_HDA_o) { std::cerr << "null: TVPPsColorDodgeBlend_HDA_o\n"; ++missing; }
  if (!TVPPsColorDodge5Blend) { std::cerr << "null: TVPPsColorDodge5Blend\n"; ++missing; }
  if (!TVPPsColorDodge5Blend_o) { std::cerr << "null: TVPPsColorDodge5Blend_o\n"; ++missing; }
  if (!TVPPsColorDodge5Blend_HDA) { std::cerr << "null: TVPPsColorDodge5Blend_HDA\n"; ++missing; }
  if (!TVPPsColorDodge5Blend_HDA_o) { std::cerr << "null: TVPPsColorDodge5Blend_HDA_o\n"; ++missing; }
  if (!TVPPsColorBurnBlend) { std::cerr << "null: TVPPsColorBurnBlend\n"; ++missing; }
  if (!TVPPsColorBurnBlend_o) { std::cerr << "null: TVPPsColorBurnBlend_o\n"; ++missing; }
  if (!TVPPsColorBurnBlend_HDA) { std::cerr << "null: TVPPsColorBurnBlend_HDA\n"; ++missing; }
  if (!TVPPsColorBurnBlend_HDA_o) { std::cerr << "null: TVPPsColorBurnBlend_HDA_o\n"; ++missing; }
  if (!TVPPsLightenBlend) { std::cerr << "null: TVPPsLightenBlend\n"; ++missing; }
  if (!TVPPsLightenBlend_o) { std::cerr << "null: TVPPsLightenBlend_o\n"; ++missing; }
  if (!TVPPsLightenBlend_HDA) { std::cerr << "null: TVPPsLightenBlend_HDA\n"; ++missing; }
  if (!TVPPsLightenBlend_HDA_o) { std::cerr << "null: TVPPsLightenBlend_HDA_o\n"; ++missing; }
  if (!TVPPsDarkenBlend) { std::cerr << "null: TVPPsDarkenBlend\n"; ++missing; }
  if (!TVPPsDarkenBlend_o) { std::cerr << "null: TVPPsDarkenBlend_o\n"; ++missing; }
  if (!TVPPsDarkenBlend_HDA) { std::cerr << "null: TVPPsDarkenBlend_HDA\n"; ++missing; }
  if (!TVPPsDarkenBlend_HDA_o) { std::cerr << "null: TVPPsDarkenBlend_HDA_o\n"; ++missing; }
  if (!TVPPsDiffBlend) { std::cerr << "null: TVPPsDiffBlend\n"; ++missing; }
  if (!TVPPsDiffBlend_o) { std::cerr << "null: TVPPsDiffBlend_o\n"; ++missing; }
  if (!TVPPsDiffBlend_HDA) { std::cerr << "null: TVPPsDiffBlend_HDA\n"; ++missing; }
  if (!TVPPsDiffBlend_HDA_o) { std::cerr << "null: TVPPsDiffBlend_HDA_o\n"; ++missing; }
  if (!TVPPsDiff5Blend) { std::cerr << "null: TVPPsDiff5Blend\n"; ++missing; }
  if (!TVPPsDiff5Blend_o) { std::cerr << "null: TVPPsDiff5Blend_o\n"; ++missing; }
  if (!TVPPsDiff5Blend_HDA) { std::cerr << "null: TVPPsDiff5Blend_HDA\n"; ++missing; }
  if (!TVPPsDiff5Blend_HDA_o) { std::cerr << "null: TVPPsDiff5Blend_HDA_o\n"; ++missing; }
  if (!TVPPsExclusionBlend) { std::cerr << "null: TVPPsExclusionBlend\n"; ++missing; }
  if (!TVPPsExclusionBlend_o) { std::cerr << "null: TVPPsExclusionBlend_o\n"; ++missing; }
  if (!TVPPsExclusionBlend_HDA) { std::cerr << "null: TVPPsExclusionBlend_HDA\n"; ++missing; }
  if (!TVPPsExclusionBlend_HDA_o) { std::cerr << "null: TVPPsExclusionBlend_HDA_o\n"; ++missing; }
  if (!TVPReverseRGB) { std::cerr << "null: TVPReverseRGB\n"; ++missing; }
  if (!TVPUpscale65_255) { std::cerr << "null: TVPUpscale65_255\n"; ++missing; }
  if (!TVPConvert32BitTo24Bit) { std::cerr << "null: TVPConvert32BitTo24Bit\n"; ++missing; }
  tjs_uint32 pixels[8] = {};
  TVPFillARGB(pixels, 8, 0xff112233u);
  for (auto pixel : pixels) if (pixel != 0xff112233u) return 2;
  tjs_uint32 source[8];
  for (auto &pixel : source) pixel = 0x00887766u;
  TVPCopyOpaqueImage(pixels, source, 8);
  for (auto pixel : pixels) if (pixel != 0xff887766u) return 3;
  for (auto &pixel : source) pixel = 0x00ff0000u;
  TVPAlphaBlend_HDA(pixels, source, 8);
  for (auto pixel : pixels) if (pixel != 0xff887766u) return 4;
  for (auto &pixel : source) pixel = 0x80ff0000u;
  TVPAlphaBlend_HDA(pixels, source, 8);
  for (auto pixel : pixels) {
    const auto red = (pixel >> 16) & 255u;
    const auto green = (pixel >> 8) & 255u;
    const auto blue = pixel & 255u;
    if (red <= 0x88u || red >= 255u || green >= 0x77u || blue >= 0x66u) return 5;
  }
  std::cout << "function pointers checked: 265\nnull pointers: " << missing
            << "\nfill/copy/transparent-alpha/half-alpha operations passed\n";
  TVPUninitTVPGL();
  return missing ? 1 : 0;
}
